#!/bin/bash

set -e
SBCL_HOME=/root/.roswell/impls/x86-64/linux/sbcl-bin/2.4.10/lib/sbcl \
sbcl --no-sysinit --no-userinit --non-interactive \
     --eval "(push #p\"/root/quicklisp/local-projects/\" ql:*local-project-directories*)" \
     --eval "(ql:register-local-projects)" \
     --eval "(format t \"~%Loading main ichiran system...~%\")" \
     --eval "(ql:quickload :ichiran)" \
     --eval "(format t \"~%Loading web system...~%\")" \
     --eval "(ql:quickload :ichiran/web)" \
     --eval "(format t \"~%Verifying packages...~%\")" \
     --eval "(format t \"Packages loaded: ~a~%\" (find-package :ichiran/web))" \
     --eval "(ichiran/mnt:add-errata)" \
     --eval "(in-package :ichiran/all)" \
     --eval "(init-all-caches)" \
     --eval "(init-suffixes t)" \
     --eval "(postmodern:clear-connection-pool)" \
     --eval "(format t \"~%Saving core file...~%\")" \
     --eval "(uiop:dump-image \"/root/ichiran.core\" :executable t :compression t)"