#!/bin/bash

echo "Starting web server..."
SBCL_HOME=/root/.roswell/impls/x86-64/linux/sbcl-bin/2.4.10/lib/sbcl \
exec /root/.roswell/impls/x86-64/linux/sbcl-bin/2.4.10/bin/sbcl \
     --core /root/ichiran.core \
     --no-sysinit --no-userinit \
     --eval "(ichiran/web:start-server)" \
     --eval "(loop (sleep 1))"